# License: CC0-1.0
general:
  name: 'WeMove'

default:
  image:
    profile: /images/fallback/wemove.min.svg
    nonprofit: /images/fallback/wemove.min.svg
    campaign: /fallback/default-campaign-background.jpg

image:
  host: https://s3.eu-central-1.amazonaws.com/commitchange-wemove/
  region: eu-central-1

mailer:
  default_from: "WeMove Team <info@wemove.eu>"
  email: "info@wemove.eu"

devise:
  mailer_sender: "donation@wemove.eu"

payment_provider:
  stripe_connect: false

intntl:
  currencies: ["eur"]
  eur:
    unit: "euro"
    subunit: "cents"
    symbol: "€"
    abbv: "eur"
    format: "%n%u"
  gbp:
    unit: "pound"
    subunit: "cents"
    symbol: "£"
    abbv: "gbp"
    format: "%n%u"
  pln:
    unit: "złoty"
    subunit: "groszy"
    symbol: "zł"
    abbv: "pln"
    format: "%n%u"

  all_countries: [AL, AT, BE, BG, CH, CY, CZ, DE, DK, EE, ES, FI, FR, GB, GR, HR, HU, IE, IS, IT, LT, LU, LV, ME, MK, MT, NL, 'NO', PL, PT, RO, RS, SE, SI, SK, TR]
  other_country: ZZ


integration:
  type: "civic_crm"
  host: "lem.wemove.eu"
  vhost: "data_api"
  user: "commitchange"
  password: "<%= ENV.fetch('CIVIC_CRM_RABBITMQ_PASSWORD') %>"
  exchange: "commitchange"
  routing_key: "commitchange.donations"

language: "en"
available_locales: ["en", "fr", "de","it","pl","es", "ro"]
show_state_field: false
