# License: CC0-1.0
version: '2'
services:
  web:
    build:
      context: ../..
      dockerfile: docker/debug/Dockerfile
      args:
      - USER
    user: ${USER}

    environment:
    - DATABASE_HOST=db
    - MEMCACHE_SERVERS=memcached
    - USER=${USER}

    volumes:
    - ../../:/myapp

    ports:
    - "5000:5000"
    depends_on:
    - db
    - memcached
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
  memcached:
    image: memcached






